### ISSUE TITLE
Remove caching recommendation

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#283]
We have type-aware rules enabled, so [we should turn it off](https://typescript-eslint.io/troubleshooting/faqs/eslint/#can-i-use-eslints---cache-with-typescript-eslint).

**Comment by AndreaPontrandolfo** [comment]
Didn't know about this.
This is interesting _and_ disappointing, lol.
@lishaduck great catch!

If you or anybody else want to PR this, PRs are welcome. Otherwise i'll do this myself.

Although, i would be more inclined to just comment (`/* */`) the existing docs, rather than deleting them, just in case.
