### ISSUE TITLE
How do I override plugin rules for unsupported file types?

### ISSUE THREAD

**Issue by chalkygames123** [AndreaPontrandolfo/sheriff#45]
Hi, thank you for creating this config. It's promising!

So I'm struggling to override plugin rules for all files, including the ones Sheriff doesn't support.

For example, with the following config that overrides `react/jsx-sort-props` rule for all files:

```js
// eslint.config.js
import sheriff from 'eslint-config-sheriff';
import { defineFlatConfig } from 'eslint-define-config';

const sheriffOptions = {
	react: true,
	lodash: false,
	next: false,
	playwright: false,
	jest: false,
	vitest: false,
};

export default defineFlatConfig([
	...sheriff(sheriffOptions),
	{
		rules: {
			'react/jsx-sort-props': [
				2,
				{
					ignoreCase: true,
					callbacksLast: true,
					shorthandLast: true,
					noSortAlphabetically: true,
					reservedFirst: true,
				},
			],
		},
	},
	{
		files: ['**/*.astro'],
	},
]);
```

`npx eslint --print-config src/pages/index.astro` will get an error:

```
Oops! Something went wrong! :(

ESLint: 8.45.0

TypeError: Key "rules": Key "react/jsx-sort-props": Could not find plugin "react".
```

As a workaround, manually adding the missing plugin will work:

```diff js
// eslint.config.js
import sheriff from 'eslint-config-sheriff';
import { defineFlatConfig } from 'eslint-define-config';
+import react from 'eslint-plugin-react';

const sheriffOptions = {
	react: true,
	lodash: false,
	next: false,
	playwright: false,
	jest: false,
	vitest: false,
};

export default defineFlatConfig([
	...sheriff(sheriffOptions),
	{
		rules: {
			'react/jsx-sort-props': [
				2,
				{
					ignoreCase: true,
					callbacksLast: true,
					shorthandLast: true,
					noSortAlphabetically: true,
					reservedFirst: true,
				},
			],
		},
	},
	{
		files: ['**/*.astro'],
+		plugins: {
+			react,
+		},
	},
]);
```

This may just be the standard behavior of flat config, but I'm wondering if there is a more "correct" solution.

Any advice would be greatly appreciated 🙏

**Comment by AndreaPontrandolfo** [comment]
Hey man, appreciated! 
No, you definitely shouldn't need to import eslint-plugin-react. It should work right away. So there must be something wrong with your setup.
I need to gather more info. A few questions:
- are you using npm to manage dependencies?
- is your project a monorepo?
- if you go into the node_modules of your current working directory, do you see eslint-plugin-react?

**Comment by chalkygames123** [comment]
Thank you for the quick response!

> are you using npm to manage dependencies?

Yes.

> is your project a monorepo?

No.

> if you go into the node_modules of your current working directory, do you see eslint-plugin-react?

Yes.


Reproduction repo here: https://github.com/chalkygames123/repro-sheriff-override-plugin-rules-for-unsupported-file-types

**Comment by AndreaPontrandolfo** [comment]
Thanks for the reproduction repo. Linting the jsx file worked perfectly. With the Astro file instead, the ouput was: 
`0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`
Which is expected, i guess, because the files matched by Sheriff are `js,mjs,cjs,ts,mts,cts,jsx,tsx,mtsx,mjsx`, and so, .astro files are ignored because never matched.
I noticed the are a few things going on here. I'll share my thinkings with you, so we can work towards the solution:
- you do this
	```javascript
		 {
			files: ['**/*.astro'],
		},
	``` 
	This is incorrect. When you declare the files, you also have to attach something else to it (like the rules), otherwise it simply 		goes void. You think you are saying: "Execute this config on every .astro file", but that's not what is happening. If you wanted those react rules in the astro files, you should have done this:
	```javascript
    {
      files: ['**/*.astro'],
      rules: {
			'react/jsx-sort-props': [
				2,
				{
					ignoreCase: true,
					callbacksLast: true,
					shorthandLast: true,
					noSortAlphabetically: true,
					reservedFirst: true,
				},
			],
      },
    },
	``` 
- in the reproduction repo you are missing typescript. Sheriff only work in Typescript projects, it expects a typescript dependency and a valid tsconfig file in the project, otherwise things might not work. It's important.
- as said before, Sheriff doesn't really support astro right now. I could incorporate [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) into Sheriff and support .astro files, just know that it's expected to not work at this moment.

**Comment by chalkygames123** [comment]
I over-reduced the reproduction repo. Sorry for the confusion. I elaborate on it to use TypeScript and to make `.astro` files can be parsed.

I couldn't find any mention of it in the official documentation, but a configuration object that specifies only `files` will add the target files for lint, just like the `--ext` option in the CLI or `overrides` in eslintrc. That said, there are additional properties (`plugins` and `languageOptions`) now because they are required here for the `.astro` files to be parsed.

To clarify, I don't want to override the rules "only" for `.astro` files, but for all files, including `.astro` files. That's why I included the React rules in the configuration object without `files`.

While it is cool to incorporate `eslint-plugin-astro` into Sheriff, it is not as popular as the other libraries/frameworks that Sheriff supports, so I am okay with it if it is not incorporated.

**Comment by chalkygames123** [comment]
Sorry, forgot to push. Now up to date.

**Comment by AndreaPontrandolfo** [comment]
Hey [chalkygames123](https://github.com/chalkygames123 )!
I updated the repro. It works perfectly now, both with the CLI command and with the editor integration. Let me know if you think something is still missing.

https://github.com/AndreaPontrandolfo/repro-sheriff-override-plugin-rules-for-unsupported-file-types
Just a few random notes:
- i noticed you used npm in the repro. I would recomend to switch to pnpm, i can guarantee you it will make your life way easier. Its crazy good.
- i noticed you set `allowJs: true` in the tsconfig. I would recommend to keep your projects full typescript and so you shouldn't need this flag. Its probably not too dangerous to have it on, but i prefer to have it off.  
- take special care with the JSX rules because the docs say that their support in the astro-parser is limited: https://github.com/ota-meshi/astro-eslint-parser#handshake-compatibility-with-existing-eslint-rules . In the repro i used the one that they suggest in the docs.

> I couldn't find any mention of it in the official documentation, but a configuration object that specifies only files will add the target files for lint, just like the --ext option in the CLI or overrides in eslintrc. That said, there are additional properties (plugins and languageOptions) now because they are required here for the .astro files to be parsed.
> 
> To clarify, I don't want to override the rules "only" for .astro files, but for all files, including .astro files. That's why I included the React rules in the configuration object without files.

About this, again, i don't think this is how the FlatConfig works or how it should be used. Or maybe we have a misunderstanding on this.
Point is, like i said in my past comment, Sheriff right now doesn't really support .astro files. Its currently basically impossible to apply Sheriff rules to astro files because i didnt include `.astro` in the files array.
But again, its not a problem, i'll include direct support for it. Give me a couple of days.
